db:
  image: mongo
  volumes:
    - ./data/db:/data/db
web:
  build: .
  command: python /gsf/manage.py runserver 0.0.0.0:8000
  volumes:
    - ./gsf:/gsf
  ports:
    - "8000:8000"
  links:
    - db
